# .github/workflows/deploy.yml
name: Deploy Log Processing Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY1 }}
      AWS_REGION: us-east-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var-file="environments/${{ github.ref_name }}.tfvars"

  deploy:
    needs: terraform-plan
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -var-file="environments/prod.tfvars"

      - name: Upload Lambda code to S3
        run: |
          aws s3 cp lambda_code/ingest_lambda.py s3://assignment5-lambda-code/ --region $AWS_REGION

      - name: Upload Glue script to S3
        run: |
          aws s3 cp etl/etl_script.py s3://assignment5-glue-script/ --region $AWS_REGION
